FROM python:3-alpine

# Create app directory
EXPOSE 8083
EXPOSE 8084

RUN apk --update add build-base libffi-dev openssl-dev python-dev py-pip
RUN pip install cryptography

# COPY . .
ADD TCP_UDPsocketServer.py /app

WORKDIR /app

CMD [ "python", "TCP_UDPsocketServer.py" ]


